### ISSUE TITLE
Taxonomy routes can't be processed

### ISSUE THREAD

**Issue by pdipatrizio** [jacksleight/statamic-bonus-routes#1]
The `if` statement in Router.php is checking for `collection` twice, making it impossible for Taxonomy routes to be processed.

The `else if` on line 41 should be `$mode === 'taxonomy'`.

https://github.com/jacksleight/statamic-bonus-routes/blob/6850e7ab2291be506804555e33dab88f276c51ac/src/Mixins/Router.php#L41

**Comment by jacksleight** [comment]
Whoops, thanks for investigating and reporting! Fixed in v0.1.1.
